import sys
import json
import marshal
import logging

# The google API has some features like helpers, builders, reflection...
from google.protobuf import json_format, timestamp_pb2

# We can import our data structures generated by Protocol Buffer
from pb.generated.sub.sub_demo_pb2 import (
    ReportResponse,
    ActionType,
    WarningMsgType,
    Measure,
    WarningMsg,
    RequestReport,
    RequestAction,
    RequestSetConfig,
    ApiResponse,
)
import helpers

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)


def main():
    # Create a report with fake data
    report = helpers.generate_reports(1000)
    # Convert data to binary
    pb_bin_out = report.SerializeToString()
    # Compare size of data to raw json and regular marshalling
    json_pretty_out = json_format.MessageToJson(report)
    json_python = json.loads(json_pretty_out)
    json_mini_out = json.dumps(json_python, indent=None, separators=(",", ":"))
    json_marshal_out = marshal.dumps(json_python)
    print(f"JSON str prettyfy:\t{len(json_pretty_out)} bytes")
    print(f"JSON str minify\t\t{len(json_mini_out)} bytes")
    print(f"Python Marshal bin:\t{len(json_marshal_out)} bytes")
    print(f"Protocol Buffer bin:\t{len(pb_bin_out)} bytes")
    # Convert binary back to json
    new_report = ReportResponse()
    new_report.ParseFromString(pb_bin_out)
    # We get the same data
    assert new_report == report
    return 0


def optional_field():
    report = ReportResponse()
    report.measures.add(
        temp=25.0,
        humidity=50,
        # pressure=0,
    )
    pb_bin_out = report.SerializeToString()
    new_report = ReportResponse()
    new_report.ParseFromString(pb_bin_out)
    try:
        print(new_report.measures[0].pressure)
        print(new_report.measures[0].HasField("pressure"))
    except ValueError as e:
        print(e)


if __name__ == "__main__":
    sys.exit(main())
    # sys.exit(optional_field())
